TextFontFolderName=tfontchs

; DateTimeFormat is YYYYMMDD or DDMMYYYY or MMDDYYYY.
DateTimeFormat=YYYYMMDD

; ----------------------------

CD_CheckDisk_Start=开始进行简易磁盘检查...
CD_CheckDisk_End=简易磁盘检查结束。

CD_FatalError_Title=!!发现了严重的磁盘错误!!
CD_FatalError_DuplicatedArea0=有文件重叠区域。
CD_FatalError_DuplicatedArea1=部分文件夹已损坏。
CD_FatalError_BrokenEntry0=目录进入异常。
CD_FatalError_BrokenEntry1=一个以上的文件夹已损坏。
CD_FatalError_IlligalClusterLink0=簇/群集的规格不合法
CD_FatalError_IlligalClusterLink1=有文件夹损坏的可能性
CD_FatalError_BrokenDirectoryLink0=目录夹排名有异常
CD_FatalError_BrokenDirectoryLink1=文件夹已损坏
CD_FatalError_BrokenUnicode0=目录夹排名有异常
CD_FatalError_BrokenUnicode1=长文件名被破坏
CD_FatalError_FileSizeError0=目录进入显示的容量大小
CD_FatalError_FileSizeError1=和实际的文件夹容量大小不同
CD_FatalError_UnknownError=未知错误
CD_FatalError_RecoveryMsg0=恢复方法:
CD_FatalError_RecoveryMsg1=将硬盘里备份的所有相关数据
CD_FatalError_RecoveryMsg2=重新拷贝到磁盘
CD_FatalError_StopApplication=终止应用软件

CD_NotSupportDiskSize_Title=无法处理的磁盘格式
CD_NotSupportDiskSize_Msg0=磁盘容量是否过大
CD_NotSupportDiskSize_Msg1=或簇单元过小
CD_NotSupportDiskSize_Msg2=
CD_NotSupportDiskSize_RecoveryMsg0=恢复方法:
CD_NotSupportDiskSize_RecoveryMsg1=请使用更大的簇单元
CD_NotSupportDiskSize_RecoveryMsg2=尝试重新格式化
CD_NotSupportDiskSize_RecoveryMsg3=


CD_CheckDuplicateCluster_Title=检查重复簇和碎片
CD_CheckFATType_Title=检查FAT格式
CD_FATType_UnknownFATType=是不能兼容的FAT格式
CD_WriteError_Title=磁盘读写测试失败
CD_WriteError_Msg0=磁盘可用空间不足
CD_WriteError_Msg1=没有对应的驱动程序
CD_WriteError_Msg2=CF/SD和适配器的相容性或接触不良
CD_WriteError_Msg3=磁盘管理区域已损坏
CD_WriteError_Msg4=
CD_WriteError_Msg5=等,几种原因
CD_WriteError_Msg6=
CD_WriteError_Msg7=安全结束应用软件
CD_WriteTest_Title=进行磁盘读写试验



; ----------------------------

ERRMSG0_MemoryOverflow_CanRecovery=由于内存不足而产生错误，
ERRMSG1_MemoryOverflow_CanRecovery=无法打开文件。。
ERRMSG2_MemoryOverflow_CanRecovery=点击此窗口关闭

ERRMSG0_NotSupportFileFormat=不支持的文件格式，
ERRMSG1_NotSupportFileFormat=或者文件已损坏。
ERRMSG2_NotSupportFileFormat=点击此窗口关闭

ERRMSG0_ProgressiveJpeg=不兼容的
ERRMSG1_ProgressiveJpeg=JPEG文件类型
ERRMSG2_ProgressiveJpeg=点击此窗口关闭

ERRMSG0_Text0byte=空白文本文件，
ERRMSG1_Text0byte=0字节的文件不能打开。。
ERRMSG2_Text0byte=点击此窗口关闭

ERRMSG0_OverflowLargeImage=图片尺寸太大，
ERRMSG1_OverflowLargeImage=最大支持约500万像素的图片
ERRMSG2_OverflowLargeImage=点击此窗口关闭

ERRMSG0_NotFoundMusicFile=无法找到
ERRMSG1_NotFoundMusicFile=指定文件夹的音乐文件
ERRMSG2_NotFoundMusicFile=点击此窗口关闭

ERRMSG0_UnknownError=发生一个未定义的错误
ERRMSG1_UnknownError=内部异常
ERRMSG2_UnknownError=请关闭电源

; ----------------------------

Setup_Help0=MoonShell Version 2.00
Setup_Help1=
Setup_Help2=
Setup_Help3=请设置一下项目
Setup_Help4=
Setup_Help5=设置完成后 以后需要使用时
Setup_Help6=可以在主菜单按下START键、
Setup_Help7=在系统设置中打开
Setup_Help8=
Setup_Help9=按键说明请参照
Setup_Help10=压缩包内的“按键说明”
Setup_Help11=

Setup_BootCheckDisk=每次开机都检查磁盘错误
Setup_ClickSound=启用按键效果音
Setup_FileListMode=文件名显示方式
Setup_FileListMode_Single=总是以单行显示
Setup_FileListMode_Double=当文件名超出屏幕时自动换行
Setup_LRClickLongSeek=长按R和十字键调整MP3进度条
Setup_SkipSetup=下次启动时不显示初始化界面
Setup_OKBtn=

; ----------------------------

Launch_FileInfo=文件信息
Launch_FileInfo_Relational=关联文件信息
Launch_Size=大小： %dbyte (%dMbit)
Launch_Create=创建日期： %s %d:%02d:%02d
Launch_Update=修改时间： %s %d:%02d:%02d
Launch_NotFoundRelationalFile=Not found relational file.

; ----------------------------

FL_DeleteFileDialog_Question_Title=文件删除
FL_DeleteFileDialog_Question_Line0=真的要删除这个文件吗？
FL_DeleteFileDialog_Question_Line1=L+R+A键确认
FL_DeleteFileDialog_Question_Line2=B键取消

FL_DeleteFileDialog_Success_Title=文件删除
FL_DeleteFileDialog_Success_Line0=
FL_DeleteFileDialog_Success_Line1=文件删除完毕
FL_DeleteFileDialog_Success_Line2=

; ----------------------------

; Not impliments this. (for sub menu)

FLSM_Folder_AllPlay=播放文件夹内所有曲目

FLSM_Text_CharCode_Auto=打开自动检测编码
FLSM_Text_CharCode_ANSI=打开ANSI模式
FLSM_Text_CharCode_UTF8=打开UTF-8模式
FLSM_Text_CharCode_SJIS=打开GBK模式
FLSM_Text_CharCode_UTF16BE=打开UTF-16BE模式
FLSM_Text_CharCode_UTF16LE=打开UTF-16LE模式

FLSM_NDSROM_ExtendBoot=使用扩展模式

; ----------------------------

SM_FileListMode=文件列表模式切换
SM_Customize=系统设定
SM_RestoreBG=还原壁纸
SM_Firmware=返回烧录卡内核界面
SM_Firmware_NotFound=未找到 %s

; ----------------------------

CS_Help0=进行系统和音乐相关的设置
CS_Help1=
CS_Help2=
CS_Help3=要进行图片，DPG 文本相关的设定
CS_Help4=请在相关文件打开或播放的状态下
CS_Help5=按SELECT键进入设置
CS_Help6=
CS_Help7=
CS_Help8=电脑上使用安装Moonshell程序
CS_Help9=还可以配置几个设置
CS_Help10=
CS_Help11=

CS_Title=MoonShell2 系统设置

CS_SkipSetup=启动时不显示设定窗口
CS_BootCheckDisk=启动时进行磁盘检查

CS_ClickSound=按键声音打开
CS_EnableFadeEffect=画面切换有过渡效果
CS_AutoLastState=允许启动时自动打开收藏夹


CS_MoveFolderLocked=锁定当前文件夹，禁止切换
CS_HiddenFilenameExt=隐藏文件的扩展名
CS_HiddenNotSupportFileType=隐藏不支持的文件
CS_ScreenSaver_BlackMode=屏幕保护使用最低亮度等级显示
CS_DisableLRKeyOnPanelClosed=闭合NDS(L)后自动禁止使用L/R键
CS_LRClickLongSeek=长按R和十字键控制MP3进度条

CS_ShowID3Tag=播放 MP3 时显示 ID3Tag 标签

CS_Cancel=取消
CS_Ok=确定

; ----------------------------

DCS_Help0=进行 DPG 播放相关的设置
DCS_Help1=
DCS_Help2=
DCS_Help3=选择快速打开DPG文件选项、
DCS_Help4=高帧数、高比特率的文件
DCS_Help5=再次播放时可能放缓
DCS_Help6=
DCS_Help7=
DCS_Help8=
DCS_Help9=
DCS_Help10=
DCS_Help11=

DCS_Title=DPG播放模式设置

DCS_EnabledFastStart=快速打开 DPG 文件
DCS_PauseWhenPanelClosed=播放时合上 DS 则暂停播放

DV_VolumeLabel=Vol.
DV_VolumeValue=%d%%
DV_VolumeMute=MUTE
DV_VolumeMax=MAX

; ----------------------------

ICS_Help0=进行图片显示相关的设置
ICS_Help1=
ICS_Help2=
ICS_Help3=图片显示时按下START键
ICS_Help4=就可以将当前图片设置为壁纸
ICS_Help5=
ICS_Help6=想放弃设置的壁纸的话
ICS_Help7=你可以在主界面按下START键
ICS_Help8=在弹出的子菜单中
ICS_Help9=选择「还原壁纸」
ICS_Help10=
ICS_Help11=

ICS_Title=图片显示模式设置

ICS_ShowInfomation=显示文件属性和帮助
ICS_ShowControlIcons=显示触摸屏操作图示
ICS_DoubleSpeedKey=灵敏按键操作
ICS_DoubleSpeedTouch=灵敏触摸屏操作
ICS_MultipleResume=记忆缩放比 在启动时还原
ICS_AutoFitting=Jpeg图片过大自适应缩小
ICS_EffectTitle=转换成壁纸时的效果
ICS_EffectHeightPadding=考虑上下画面间隔转换
ICS_EffectPastelForTopBG=上画面应用粉彩效果加工
ICS_EffectPastelForBottomBG=下画面应用粉彩效果加工

; ----------------------------

IV_LoadMsg0=正在读取图片文件
IV_LoadMsg1=请稍候

IV_Help1=START: 选择壁纸 / SELECT: 选项设定
IV_Help2=Ｙ:50% / Ｘ:100% / Ａ:200% / Ｂ:返回

; ----------------------------

TCS_Help0=进行文件显示相关的设置
TCS_Help1=
TCS_Help2=・ClearType 字体使用须知
TCS_Help3=老版NDS当上画面也显示文字时
TCS_Help4=上画面可能变得非常模糊
TCS_Help5=
TCS_Help6=・文字编码自动识别失败时
TCS_Help7=在文件上长按A键或触摸屏
TCS_Help8=会弹出子菜单
TCS_Help9=在其中选择需要的编码
TCS_Help10=您可以手动设置每个文本文件
TCS_Help11=（貌似未做成）

TCS_Title=文本显示方式设置

TCS_TopScrModeTitle=上屏显示设定
TCS_TopScrModeLightOff=关闭
TCS_TopScrModeText=显示文本
TCS_TopScrModeClock=显示时钟

TCS_ScreenSaver_BlackMode=屏幕保护使用最低亮度等级显示

TCS_LineSpaceTitle=行距设定
TCS_LineSpaceSmall=狭窄
TCS_LineSpaceMiddle=标准
TCS_LineSpaceLarge=大

TCS_FontSizeTitle=文字大小
TCS_FontSizeSmall=小
TCS_FontSizeMiddle=中
TCS_FontSizeLarge=大

TCS_FontSizeTitle=字体大小
TCS_FontSizeSmall=小
TCS_FontSizeMiddle=中
TCS_FontSizeLarge=大

TCS_ClearTypeFont=使用 ClearType 字体

TCS_CPTitle=页面代码
TCS_CP437=437
TCS_CP850=850
TCS_CP1252=1252

TCS_DetectCharCodeTitle=自动选择文字编码
TCS_DetectCharCode_ANSI=ANSI (8bit ASCII)
TCS_DetectCharCode_SJIS=简体中文(GBK)
TCS_DetectCharCode_UTF16BE=UTF-16 big endian
TCS_DetectCharCode_UTF16LE=UTF-16 little endian
TCS_DetectCharCode_UTF8=UTF-8

; ----------------------------

; ----------------------------
BOOT_processing_save=没有找到存档文件，创建存档中，请稍候
BOOT_processing_load=正在读取存档文件，请稍候
BOOT_LoadingNDS=载入NDS文件，稍侯
STS_Gaming=游戏
STS_Mshell20=多媒体

STS_Slot2=启动GBA
; ----------------------------
FL_Language=Chinese Verison
FL_File_Date=最后写入：
FL_Button_Cheat=金手指
FL_Button_Setup=设　置
FL_Folder=文件夹
FL_Updir=上级目录


;-----------
M3_Menu=GM管理
M3_Card=我的存储卡
M3_Card_Name=名字
M3_Card_Size=大小

;-------------
SET_Menu=特殊功能设置
SET_Language=语言设置
SET_CheatOnOff=金手指
SET_SoftReset=软复位 
SET_InstantSave=即时存档
SET_InstantWalk=即时攻略
SET_ButtonOK=(A)确定
SET_ButtonCancel=(B)取消

;------------------
CHEAT_Menu=金手指
CHEAT_Enable=(X)启用
CHEAT_Disable=(Y)禁止
CHEAT_Save=(A)保存
CHEAT_Cancel=(B)取消
CHEAT_End=End

