BL2CK_1.31.0.zip: directory
	mkdir tmp;
	cp -r $(COMMON)/BL2CK/BL2CK_common/* $(COMMON)/BL2CK/R4iTT/_ds_menu.dat $(COMMON)/BL2CK/R4iTT/akmenu4.nds $(COMMON)/BL2CK/R4iTT/__rpg tmp/
	cd tmp; zip -r $(OUT)/$(BASE)/$@ *
	rm -rf tmp
