BL2CK_1.31.0_Amaze3DS.zip: directory
	mkdir tmp;
	cp -r $(COMMON)/BL2CK/BL2CK_common/* $(COMMON)/BL2CK/Amaze3DS/_ds_menu.dat $(COMMON)/BL2CK/Amaze3DS/akmenu4.nds $(COMMON)/BL2CK/Amaze3DS/__rpg tmp/
	cd tmp; zip -r $(OUT)/$(BASE)/$@ *
	rm -rf tmp
