BL2CK_1.31.0_EDGEi.zip: directory
	mkdir tmp;
	cp -r $(COMMON)/BL2CK/BL2CK_common/* $(COMMON)/BL2CK/EDGEi/dsedgei.dat $(COMMON)/BL2CK/EDGEi/akmenu4.nds $(COMMON)/BL2CK/EDGEi/__rpg tmp/
	cd tmp; zip -r $(OUT)/$(BASE)/$@ *
	rm -rf tmp
