BL2CK_1.30.4_EDGEi.zip: directory
	mkdir tmp;
	cp -r $(COMMON)/BL2CK/BL2CK_common/* $(COMMON)/BL2CK/R4iTT/_ds_menu.dat $(COMMON)/BL2CK/EDGEi/dsedgei.dat tmp/
	cd tmp; zip -r $(OUT)/$(BASE)/$@ *
	rm -rf tmp
