BL2CK_1.31.0_r4dspro.com.zip: directory
	mkdir tmp;
	cp -r $(COMMON)/BL2CK/BL2CK_common/* $(COMMON)/BL2CK/r4dspro.com/_ds_menu.dat $(COMMON)/BL2CK/r4dspro.com/akmenu4.nds $(COMMON)/BL2CK/r4dspro.com/__rpg tmp/
	cd tmp; zip -r $(OUT)/$(BASE)/$@ *
	rm -rf tmp
